[theme]
primaryColor = "#66c0f4"
backgroundColor = "#1b2838"
secondaryBackgroundColor = "#171a21"
textColor = "#c7d5e0"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
